### ISSUE TITLE
Questions about the Rotated 3DMatch/3DLoMatch results in YOHO

### ISSUE THREAD

**Issue by clavichord93** [HpWang-whu/YOHO#2]
Hi Haiping,

I notice that in Tab.1 of your paper, all baselines achieve similar results with or without arbitrary rotations. However, I tried to test some baselines (D3Feat and Predator) by adding arbitrary rotations to the input point clouds, they all suffer from significant performance degradation (~10% on 3DMatch and ~20% on 3DLoMatch). So I am wondering how you add rotations in your experiments and how you evaluate the results. And do you recompute the ground truth .info files?

<img width="513" alt="image" src="https://user-images.githubusercontent.com/5952339/140636652-509e52d0-cf03-4626-a52e-96f963e7c858.png">

**Comment by HpWang-whu** [comment]
Hi Zheng Qin:
Thanks for your attention. According to your concerns:
(1) The random rotation we add comes from the random rotation vector(utils.utils-->random_rotation_matrix()).
(2) Instead of recomputing the info file, the computational process of RR for the rotated version is performed directly by selecting the ground truth point pairs.​
(3) It could be the case that the FMR and IR results are similar in both dataset versions, but the RR has decreased (using the .info file recomputed), I think it should be the approximate calculation that exists in the calculation process of the info file, leading to an error in the case of random rotation.
(4) Another simple but robust way to verify is to compare the ground truth transformation and the predicted transformation directly, just like pointDSC, without considering the directly adjacent point cloud pairs, the results could be similar.

**Comment by clavichord93** [comment]
Thanks, Haiping. The results are similar when the metric in PointDSC is used.

**Comment by HpWang-whu** [comment]
You are welcome and I'll close the issue.

**Comment by wendyyuu** [comment]
Thank you for providing clarification. I have a couple of questions regarding points 1 and 2.

To confirm, are you implying that the random rotation generated using the method mentioned in point 1 is applied only to the ground truth point pairs in different algorithms, such as Predator?

I appreciate your assistance in addressing these inquiries.
